In [13]:
#Q1. numpy 행열곱 연산

import numpy as np

arr1 = np.random.rand(5, 3)
arr2 = np.random.rand(3, 2)

dot = arr1 @ arr2

print(dot, dot.shape)

[[1.0178599  0.54998767]
 [0.44284687 0.16069943]
 [1.40500368 0.53091845]
 [0.51572735 0.19564738]
 [0.84479007 0.45893593]] (5, 2)


In [9]:
#Q2. numpy concatenate 연산

arr1 = np.array([[5,7], [9,11]], float)
arr2 = np.array([[2,4], [6,8]], float)

concat_1 = np.concatenate((arr1, arr2), axis=0)
concat_2 = np.concatenate((arr1, arr2), axis=1)

print(concat_1)
print(concat_2)

[[ 5.  7.]
 [ 9. 11.]
 [ 2.  4.]
 [ 6.  8.]]
[[ 5.  7.  2.  4.]
 [ 9. 11.  6.  8.]]


In [12]:
#Q3. numpy linear regression

import numpy as np

xy = np.array([[1., 2., 3., 4., 5., 6.],
                [10., 20., 30., 40., 50., 60.]])

x_train = xy[0]
y_train = xy[1]

print(x_train, x_train.shape)
print(y_train, y_train.shape)

[1. 2. 3. 4. 5. 6.] (6,)
[10. 20. 30. 40. 50. 60.] (6,)


In [14]:
#Q4. weeght와 bias를 랜덤으로 정하기

beta_gd = np.random.random(1)
bias = np.random.random(1)

print(beta_gd, bias)

[0.58927223] [0.96427464]


In [15]:
#Q5. 경사하강법으로 linear regression으로 구현

xy = np.array([[1., 2., 3., 4., 5., 6.],
               [3., 6., 9., 12., 15., 18.]])

x_train = xy[0]
y_train = xy[1]

beta_gd = np.random.random(1)
bias = np.random.random(1)

learning_rate = 0.01
for i in range(1000):
    y_pred = x_train * beta_gd + bias
    error = ((y_pred - y_train)**2).mean()
    grad = ((y_pred - y_train)*x_train).mean()
    bias -= learning_rate * (y_pred - y_train).mean()
    beta_gd -= learning_rate*grad

    if i % 100 == 0:
        print('Epoch ({:10d}/1,000 error: {:10f}, beta_gd: {:10f}, bias:{:10f}'.format(
            i, error, beta_gd.item(), bias.item()))

Epoch (         0/1,000 error:  79.633896, beta_gd:   0.841227, bias:  1.018484
Epoch (       100/1,000 error:   0.279459, beta_gd:   2.719025, bias:  1.202908
Epoch (       200/1,000 error:   0.193946, beta_gd:   2.765929, bias:  1.002106
Epoch (       300/1,000 error:   0.134599, beta_gd:   2.805002, bias:  0.834824
Epoch (       400/1,000 error:   0.093412, beta_gd:   2.837553, bias:  0.695466
Epoch (       500/1,000 error:   0.064829, beta_gd:   2.864671, bias:  0.579371
Epoch (       600/1,000 error:   0.044991, beta_gd:   2.887261, bias:  0.482656
Epoch (       700/1,000 error:   0.031224, beta_gd:   2.906081, bias:  0.402086
Epoch (       800/1,000 error:   0.021670, beta_gd:   2.921759, bias:  0.334965
Epoch (       900/1,000 error:   0.015039, beta_gd:   2.934820, bias:  0.279049
